input createUserInput {
  name: String!
  phone: String!
}
input updateUserInput {
  name: String!
}

input createProfileInput {
  about: String
  status: String
  profilePhotoUrl: String
  userId: ID!
}
input updateProfileInput {
  status: String
  profilePhotoUrl: String
  about: String
}
input createNoteInput {
  uuid: String
  text: String
}
