input createUserInput {
  name: String!
  phone: String!
}
input createProfileInput {
  status: String
  profilePhotoUrl: String
  userId: ID!
}
input updateProfileInput {
  status: String
  profilePhotoUrl: String
}
input createNoteInput {
  uuid: String
  text: String
}
