directive @logger(text: String) on FIELD_DEFINITION
directive @upperCase on FIELD_DEFINITION

type Query {
  getUsers: [User]! @logger(text: "hello World") 
  getUser(_id: ID): User!
  getProfile(_id: ID): Profile!
  getProfileForUser(userId: ID): Profile!
  getNotes: [Note]!
}
