directive @logger(text: String) on FIELD_DEFINITION
directive @upperCase on FIELD_DEFINITION

type Query {
  getUsers: [User]! @logger(text: "Rahul")
  getUser(phone: String): User!
  getProfile(_id: ID): Profile!
  getProfileForUser(userId: ID): Profile!
  getNotes: [Note]!
  getMessages: [Message]!
  getMessagesForUser(phone: String): [Message]!
}
type Subscription {
  message(to: String): Message
}
