type User {
  _id: ID!
  name: String! @upperCase
  phone: String!
  profile: Profile
}
type Test {
  text: String!
}
type Profile {
  _id: ID!
  status: String
  profilePhotoUrl: String
  userId: ID!
  user: User
  about: String
}
type InfoMessage {
  message: String
}
type Note {
  _id: ID!
  uuid: String!
  text: String!
}
type Message {
  text: String
  to: String
  from: String
}
